token:
  expiration_time: 86400000  # 1Day
  secret: user_token_2

gateway:
  ip: 192.168.1.4

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}5a7a4c014ba59e068e776ea4e8b1a00ee761d723517cfebb519154ccac44a7d6'